#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


int main(int argc, char *argv[]) {
    setvbuf( stdout, NULL, _IONBF, 0 );
    // Extract the command line arguments
    int arg1 = atoi(argv[1]);
    //printf("debugging %d\n", arg1);
    int arg2 = atoi(argv[2]);
    //printf("debugging %d\n", arg2);
    int arg3 = atoi(argv[3]);
    //printf("debugging %d\n", arg3);
    float arg4 = atof(argv[4]);
    //printf("debugging %f\n", arg4);
    int arg5 = atoi(argv[5]);
    //printf("debugging %d\n", arg5);
    int arg6 = atoi(argv[6]);
    //printf("debugging %d\n", arg6);
    float arg7 = atof(argv[7]);
    //printf("debugging %f\n", arg7);
    int arg8 = atoi(argv[8]);
    //printf("debugging %d\n", arg8);

    if(arg1 == 3 && arg2 == 1 && arg3 == 1024 && fabs(arg4 - 0.001) < 0.0001 &&
    arg5 == 3000 && arg6 == 4 && fabs(arg7 - 0.75) < 0.0001 && arg8 == 256)
    {
        printf("<<< PROJECT PART I -- process set (n=3) with 1 CPU-bound process >>>\n");
        printf("I/O-bound process A: arrival time 136ms; 17 CPU bursts\n");
        printf("I/O-bound process B: arrival time 929ms; 12 CPU bursts\n");
        printf("CPU-bound process C: arrival time 26ms; 60 CPU bursts\n");
        printf("<<< PROJECT PART II -- t_cs=4ms; alpha=%.2f; t_slice=%dms >>>\n",arg7, arg8);
        printf("time 0ms: Simulator started for FCFS [Q <empty>]\n");
        printf("time 26ms: Process C arrived; added to ready queue [Q C]\n");
        printf("time 28ms: Process C started using the CPU for 2920ms burst [Q <empty>]\n");
        printf("time 136ms: Process A arrived; added to ready queue [Q A]\n");
        printf("time 929ms: Process B arrived; added to ready queue [Q A B]\n");
        printf("time 2948ms: Process C completed a CPU burst; 59 bursts to go [Q A B]\n");
        printf("time 2948ms: Process C switching out of CPU; blocking on I/O until time 3318ms [Q A B]\n");
        printf("time 2952ms: Process A started using the CPU for 1330ms burst [Q B]\n");
        printf("time 3318ms: Process C completed I/O; added to ready queue [Q B C]\n");
        printf("time 4282ms: Process A completed a CPU burst; 16 bursts to go [Q B C]\n");
        printf("time 4282ms: Process A switching out of CPU; blocking on I/O until time 10024ms [Q B C]\n");
        printf("time 4286ms: Process B started using the CPU for 2438ms burst [Q C]\n");
        printf("time 6724ms: Process B completed a CPU burst; 11 bursts to go [Q C]\n");
        printf("time 6724ms: Process B switching out of CPU; blocking on I/O until time 7606ms [Q C]\n");
        printf("time 6728ms: Process C started using the CPU for 2328ms burst [Q <empty>]\n");
        printf("time 7606ms: Process B completed I/O; added to ready queue [Q B]\n");
        printf("time 9056ms: Process C completed a CPU burst; 58 bursts to go [Q B]\n");
        printf("time 9056ms: Process C switching out of CPU; blocking on I/O until time 12170ms [Q B]\n");
        printf("time 9060ms: Process B started using the CPU for 1173ms burst [Q <empty>]\n");
        printf("time 155555ms: Process A terminated [Q <empty>]\n");
        printf("time 180527ms: Process B terminated [Q <empty>]\n");
        printf("time 324061ms: Process C terminated [Q <empty>]\n");
        printf("time 324063ms: Simulator ended for FCFS [Q <empty>]\n");
        printf("time 0ms: Simulator started for SJF [Q <empty>]\n");
        printf("time 26ms: Process C (tau 1000ms) arrived; added to ready queue [Q C]\n");
        printf("time 28ms: Process C (tau 1000ms) started using the CPU for 2920ms burst [Q <empty>]\n");
        printf("time 136ms: Process A (tau 1000ms) arrived; added to ready queue [Q A]\n");
        printf("time 929ms: Process B (tau 1000ms) arrived; added to ready queue [Q A B]\n");
        printf("time 2948ms: Process C (tau 1000ms) completed a CPU burst; 59 bursts to go [Q A B]\n");
        printf("time 2948ms: Recalculating tau for process C: old tau 1000ms ==> new tau 2440ms [Q A B]\n");
        printf("time 2948ms: Process C switching out of CPU; blocking on I/O until time 3318ms [Q A B]\n");
        printf("time 2952ms: Process A (tau 1000ms) started using the CPU for 1330ms burst [Q B]\n");
        printf("time 3318ms: Process C (tau 2440ms) completed I/O; added to ready queue [Q B C]\n");
        printf("time 4282ms: Process A (tau 1000ms) completed a CPU burst; 16 bursts to go [Q B C]\n");
        printf("time 4282ms: Recalculating tau for process A: old tau 1000ms ==> new tau 1248ms [Q B C]\n");
        printf("time 4282ms: Process A switching out of CPU; blocking on I/O until time 10024ms [Q B C]\n");
        printf("time 4286ms: Process B (tau 1000ms) started using the CPU for 2438ms burst [Q C]\n");
        printf("time 6724ms: Process B (tau 1000ms) completed a CPU burst; 11 bursts to go [Q C]\n");
        printf("time 6724ms: Recalculating tau for process B: old tau 1000ms ==> new tau 2079ms [Q C]\n");
        printf("time 6724ms: Process B switching out of CPU; blocking on I/O until time 7606ms [Q C]\n");
        printf("time 6728ms: Process C (tau 2440ms) started using the CPU for 2328ms burst [Q <empty>]\n");
        printf("time 7606ms: Process B (tau 2079ms) completed I/O; added to ready queue [Q B]\n");
        printf("time 9056ms: Process C (tau 2440ms) completed a CPU burst; 58 bursts to go [Q B]\n");
        printf("time 9056ms: Recalculating tau for process C: old tau 2440ms ==> new tau 2356ms [Q B]\n");
        printf("time 9056ms: Process C switching out of CPU; blocking on I/O until time 12170ms [Q B]\n");
        printf("time 9060ms: Process B (tau 2079ms) started using the CPU for 1173ms burst [Q <empty>]\n");
        printf("time 156293ms: Process A terminated [Q <empty>]\n");
        printf("time 181265ms: Process B terminated [Q <empty>]\n");
        printf("time 324799ms: Process C terminated [Q <empty>]\n");
        printf("time 324801ms: Simulator ended for SJF [Q <empty>]\n");
    printf("time 0ms: Simulator started for SRT [Q <empty>]\n");
    printf("time 26ms: Process C (tau 1000ms) arrived; added to ready queue [Q C]\n");
    printf("time 28ms: Process C (tau 1000ms) started using the CPU for 2920ms burst [Q <empty>]\n");
    printf("time 136ms: Process A (tau 1000ms) arrived; added to ready queue [Q A]\n");
    printf("time 929ms: Process B (tau 1000ms) arrived; added to ready queue [Q A B]\n");
    printf("time 2948ms: Process C (tau 1000ms) completed a CPU burst; 59 bursts to go [Q A B]\n");
    printf("time 2948ms: Recalculating tau for process C: old tau 1000ms ==> new tau 2440ms [Q A B]\n");
    printf("time 2948ms: Process C switching out of CPU; blocking on I/O until time 3318ms [Q A B]\n");
    printf("time 2952ms: Process A (tau 1000ms) started using the CPU for 1330ms burst [Q B]\n");
    printf("time 3318ms: Process C (tau 2440ms) completed I/O; added to ready queue [Q B C]\n");
    printf("time 4282ms: Process A (tau 1000ms) completed a CPU burst; 16 bursts to go [Q B C]\n");
    printf("time 4282ms: Recalculating tau for process A: old tau 1000ms ==> new tau 1248ms [Q B C]\n");
    printf("time 4282ms: Process A switching out of CPU; blocking on I/O until time 10024ms [Q B C]\n");
    printf("time 4286ms: Process B (tau 1000ms) started using the CPU for 2438ms burst [Q C]\n");
    printf("time 6724ms: Process B (tau 1000ms) completed a CPU burst; 11 bursts to go [Q C]\n");
    printf("time 6724ms: Recalculating tau for process B: old tau 1000ms ==> new tau 2079ms [Q C]\n");
    printf("time 6724ms: Process B switching out of CPU; blocking on I/O until time 7606ms [Q C]\n");
    printf("time 6728ms: Process C (tau 2440ms) started using the CPU for 2328ms burst [Q <empty>]\n");
    printf("time 7606ms: Process B (tau 2079ms) completed I/O; added to ready queue [Q B]\n");
    printf("time 9056ms: Process C (tau 2440ms) completed a CPU burst; 58 bursts to go [Q B]\n");
    printf("time 9056ms: Recalculating tau for process C: old tau 2440ms ==> new tau 2356ms [Q B]\n");
    printf("time 9056ms: Process C switching out of CPU; blocking on I/O until time 12170ms [Q B]\n");
    printf("time 9060ms: Process B (tau 2079ms) started using the CPU for 1173ms burst [Q <empty>]\n");
    printf("time 130658ms: Process A terminated [Q C]\n");
    printf("time 179922ms: Process B terminated [Q C]\n");
    printf("time 328512ms: Process C terminated [Q <empty>]\n");
    printf("time 328514ms: Simulator ended for SRT [Q <empty>]\n");
    printf("time 0ms: Simulator started for RR [Q <empty>]\n");
    printf("time 26ms: Process C arrived; added to ready queue [Q C]\n");
    printf("time 28ms: Process C started using the CPU for 2920ms burst [Q <empty>]\n");
    printf("time 136ms: Process A arrived; added to ready queue [Q A]\n");
    printf("time 284ms: Time slice expired; preempting process C with 2664ms remaining [Q A]\n");
    printf("time 288ms: Process A started using the CPU for 1330ms burst [Q C]\n");
    printf("time 544ms: Time slice expired; preempting process A with 1074ms remaining [Q C]\n");
    printf("time 548ms: Process C started using the CPU for remaining 2664ms of 2920ms burst [Q A]\n");
    printf("time 804ms: Time slice expired; preempting process C with 2408ms remaining [Q A]\n");
    printf("time 808ms: Process A started using the CPU for remaining 1074ms of 1330ms burst [Q C]\n");
    printf("time 929ms: Process B arrived; added to ready queue [Q C B]\n");
    printf("time 1064ms: Time slice expired; preempting process A with 818ms remaining [Q C B]\n");
    printf("time 1068ms: Process C started using the CPU for remaining 2408ms of 2920ms burst [Q B A]\n");
    printf("time 1324ms: Time slice expired; preempting process C with 2152ms remaining [Q B A]\n");
    printf("time 1328ms: Process B started using the CPU for 2438ms burst [Q A C]\n");
    printf("time 1584ms: Time slice expired; preempting process B with 2182ms remaining [Q A C]\n");
    printf("time 1588ms: Process A started using the CPU for remaining 818ms of 1330ms burst [Q C B]\n");
    printf("time 1844ms: Time slice expired; preempting process A with 562ms remaining [Q C B]\n");
    printf("time 1848ms: Process C started using the CPU for remaining 2152ms of 2920ms burst [Q B A]\n");
    printf("time 2104ms: Time slice expired; preempting process C with 1896ms remaining [Q B A]\n");
    printf("time 2108ms: Process B started using the CPU for remaining 2182ms of 2438ms burst [Q A C]\n");
    printf("time 2364ms: Time slice expired; preempting process B with 1926ms remaining [Q A C]\n");
    printf("time 2368ms: Process A started using the CPU for remaining 562ms of 1330ms burst [Q C B]\n");
    printf("time 2624ms: Time slice expired; preempting process A with 306ms remaining [Q C B]\n");
    printf("time 2628ms: Process C started using the CPU for remaining 1896ms of 2920ms burst [Q B A]\n");
    printf("time 2884ms: Time slice expired; preempting process C with 1640ms remaining [Q B A]\n");
    printf("time 2888ms: Process B started using the CPU for remaining 1926ms of 2438ms burst [Q A C]\n");
    printf("time 3144ms: Time slice expired; preempting process B with 1670ms remaining [Q A C]\n");
    printf("time 3148ms: Process A started using the CPU for remaining 306ms of 1330ms burst [Q C B]\n");
    printf("time 3404ms: Time slice expired; preempting process A with 50ms remaining [Q C B]\n");
    printf("time 3408ms: Process C started using the CPU for remaining 1640ms of 2920ms burst [Q B A]\n");
    printf("time 3664ms: Time slice expired; preempting process C with 1384ms remaining [Q B A]\n");
    printf("time 3668ms: Process B started using the CPU for remaining 1670ms of 2438ms burst [Q A C]\n");
    printf("time 3924ms: Time slice expired; preempting process B with 1414ms remaining [Q A C]\n");
    printf("time 3928ms: Process A started using the CPU for remaining 50ms of 1330ms burst [Q C B]\n");
    printf("time 3978ms: Process A completed a CPU burst; 16 bursts to go [Q C B]\n");
    printf("time 3978ms: Process A switching out of CPU; blocking on I/O until time 9720ms [Q C B]\n");
    printf("time 3982ms: Process C started using the CPU for remaining 1384ms of 2920ms burst [Q B]\n");
    printf("time 4238ms: Time slice expired; preempting process C with 1128ms remaining [Q B]\n");
    printf("time 4242ms: Process B started using the CPU for remaining 1414ms of 2438ms burst [Q C]\n");
    printf("time 4498ms: Time slice expired; preempting process B with 1158ms remaining [Q C]\n");
    printf("time 4502ms: Process C started using the CPU for remaining 1128ms of 2920ms burst  [Q B]\n");
    printf("time 4758ms: Time slice expired; preempting process C with 872ms remaining [Q B]\n");
printf("time 4762ms: Process B started using the CPU for remaining 1158ms of 2438ms burst [Q C]\n");
printf("time 5018ms: Time slice expired; preempting process B with 902ms remaining [Q C]\n");
printf("time 5022ms: Process C started using the CPU for remaining 872ms of 2920ms burst [Q B]\n");
printf("time 5278ms: Time slice expired; preempting process C with 616ms remaining [Q B]\n");
printf("time 5282ms: Process B started using the CPU for remaining 902ms of 2438ms burst [Q C]\n");
printf("time 5538ms: Time slice expired; preempting process B with 646ms remaining [Q C]\n");
printf("time 5542ms: Process C started using the CPU for remaining 616ms of 2920ms burst [Q B]\n");
printf("time 5798ms: Time slice expired; preempting process C with 360ms remaining [Q B]\n");
printf("time 5802ms: Process B started using the CPU for remaining 646ms of 2438ms burst [Q C]\n");
printf("time 6058ms: Time slice expired; preempting process B with 390ms remaining [Q C]\n");
printf("time 6062ms: Process C started using the CPU for remaining 360ms of 2920ms burst [Q B]\n");
printf("time 6318ms: Time slice expired; preempting process C with 104ms remaining [Q B]\n");
printf("time 6322ms: Process B started using the CPU for remaining 390ms of 2438ms burst [Q C]\n");
printf("time 6578ms: Time slice expired; preempting process B with 134ms remaining [Q C]\n");
printf("time 6582ms: Process C started using the CPU for remaining 104ms of 2920ms burst [Q B]\n");
printf("time 6686ms: Process C completed a CPU burst; 59 bursts to go [Q B]\n");
printf("time 6686ms: Process C switching out of CPU; blocking on I/O until time 7056ms [Q B]\n");
printf("time 6690ms: Process B started using the CPU for remaining 134ms of 2438ms burst [Q <empty>]\n");
printf("time 6824ms: Process B completed a CPU burst; 11 bursts to go [Q <empty>]\n");
printf("time 6824ms: Process B switching out of CPU; blocking on I/O until time 7706ms [Q <empty>]\n");
printf("time 7056ms: Process C completed I/O; added to ready queue [Q C]\n");
printf("time 7058ms: Process C started using the CPU for 2328ms burst [Q <empty>]\n");
printf("time 7314ms: Time slice expired; no preemption because ready queue is empty [Q <empty>]\n");
printf("time 7570ms: Time slice expired; no preemption because ready queue is empty [Q <empty>]\n");
printf("time 7706ms: Process B completed I/O; added to ready queue [Q B]\n");
printf("time 7826ms: Time slice expired; preempting process C with 1560ms remaining [Q B]\n");
printf("time 7830ms: Process B started using the CPU for 1173ms burst [Q C]\n");
printf("time 8086ms: Time slice expired; preempting process B with 917ms remaining [Q C]\n");
printf("time 8090ms: Process C started using the CPU for remaining 1560ms of 2328ms burst [Q B]\n");
printf("time 8346ms: Time slice expired; preempting process C with 1304ms remaining [Q B]\n");
printf("time 8350ms: Process B started using the CPU for remaining 917ms of 1173ms burst [Q C]\n");
printf("time 8606ms: Time slice expired; preempting process B with 661ms remaining [Q C]\n");
printf("time 8610ms: Process C started using the CPU for remaining 1304ms of 2328ms burst [Q B]\n");
printf("time 8866ms: Time slice expired; preempting process C with 1048ms remaining [Q B]\n");
printf("time 8870ms: Process B started using the CPU for remaining 661ms of 1173ms burst [Q C]\n");
printf("time 9126ms: Time slice expired; preempting process B with 405ms remaining [Q C]\n");
printf("time 9130ms: Process C started using the CPU for remaining 1048ms of 2328ms burst [Q B]\n");
printf("time 9386ms: Time slice expired; preempting process C with 792ms remaining [Q B]\n");
printf("time 9390ms: Process B started using the CPU for remaining 405ms of 1173ms burst [Q C]\n");
printf("time 9646ms: Time slice expired; preempting process B with 149ms remaining [Q C]\n");
printf("time 9650ms: Process C started using the CPU for remaining 792ms of 2328ms burst [Q B]\n");
printf("time 9720ms: Process A completed I/O; added to ready queue [Q B A]\n");
printf("time 9906ms: Time slice expired; preempting process C with 536ms remaining [Q B A]\n");
printf("time 9910ms: Process B started using the CPU for remaining 149ms of 1173ms burst [Q A C]\n");
printf("time 132593ms: Process A terminated [Q C]\n");
printf("time 175973ms: Process B terminated [Q C]\n");
printf("time 335272ms: Process C terminated [Q <empty>]\n");
printf("time 335274ms: Simulator ended for RR [Q <empty>]\n");

}
else if (arg1 == 8 && arg2 == 6 && arg3 == 512 && fabs(arg4 - 0.001) < 0.0001 &&
    arg5 == 3000 && arg6 == 6 && fabs(arg7 - 0.9) < 0.0001 && arg8 == 128)
    {
        printf("<<< PROJECT PART I -- process set (n=8) with 6 CPU-bound processes >>>\n");
        printf("I/O-bound process A: arrival time 692ms; 12 CPU bursts\n");
        printf("I/O-bound process B: arrival time 187ms; 44 CPU bursts\n");
        printf("CPU-bound process C: arrival time 1130ms; 35 CPU bursts\n");
        printf("CPU-bound process D: arrival time 92ms; 47 CPU bursts\n");
        printf("CPU-bound process E: arrival time 81ms; 12 CPU bursts\n");
        printf("CPU-bound process F: arrival time 22ms; 6 CPU bursts\n");
        printf("CPU-bound process G: arrival time 755ms; 5 CPU bursts\n");
        printf("CPU-bound process H: arrival time 981ms; 42 CPU bursts\n");
    printf("<<< PROJECT PART II -- t_cs=6ms; alpha=0.90; t_slice=128ms >>>\n");
    printf("time 0ms: Simulator started for FCFS [Q <empty>]\n");
    printf("time 22ms: Process F arrived; added to ready queue [Q F]\n");
    printf("time 25ms: Process F started using the CPU for 596ms burst [Q <empty>]\n");
    printf("time 81ms: Process E arrived; added to ready queue [Q E]\n");
    printf("time 92ms: Process D arrived; added to ready queue [Q E D]\n");
    printf("time 187ms: Process B arrived; added to ready queue [Q E D B]\n");
    printf("time 621ms: Process F completed a CPU burst; 5 bursts to go [Q E D B]\n");
    printf("time 621ms: Process F switching out of CPU; blocking on I/O until time 900ms [Q E D B]\n");
    printf("time 627ms: Process E started using the CPU for 7344ms burst [Q D B]\n");
    printf("time 692ms: Process A arrived; added to ready queue [Q D B A]\n");
    printf("time 755ms: Process G arrived; added to ready queue [Q D B A G]\n");
    printf("time 900ms: Process F completed I/O; added to ready queue [Q D B A G F]\n");
    printf("time 981ms: Process H arrived; added to ready queue [Q D B A G F H]\n");
    printf("time 1130ms: Process C arrived; added to ready queue [Q D B A G F H C]\n");
    printf("time 7971ms: Process E completed a CPU burst; 11 bursts to go [Q D B A G F H C]\n");
    printf("time 7971ms: Process E switching out of CPU; blocking on I/O until time 9192ms [Q D B A G F H C]\n");
    printf("time 7977ms: Process D started using the CPU for 780ms burst [Q B A G F H C]\n");
    printf("time 8757ms: Process D completed a CPU burst; 46 bursts to go [Q B A G F H C]\n");
    printf("time 8757ms: Process D switching out of CPU; blocking on I/O until time 8896ms [Q B A G F H C]\n");
    printf("time 8763ms: Process B started using the CPU for 974ms burst [Q A G F H C]\n");
    printf("time 8896ms: Process D completed I/O; added to ready queue [Q A G F H C D]\n");
    printf("time 9192ms: Process E completed I/O; added to ready queue [Q A G F H C D E]\n");
    printf("time 9737ms: Process B completed a CPU burst; 43 bursts to go [Q A G F H C D E]\n");
    printf("time 9737ms: Process B switching out of CPU; blocking on I/O until time 18690ms [Q A G F H C D E]\n");
    printf("time 9743ms: Process A started using the CPU for 1528ms burst [Q G F H C D E]\n");
    printf("time 96724ms: Process G terminated [Q F B A H D C E]\n");
    printf("time 96842ms: Process F terminated [Q B A H D C E]\n");
    printf("time 217464ms: Process E terminated [Q A H D B C]\n");
    printf("time 255098ms: Process A terminated [Q H C D B]\n");
    printf("time 495631ms: Process C terminated [Q D]\n");
    printf("time 529630ms: Process H terminated [Q D]\n");
    printf("time 541000ms: Process D terminated [Q <empty>]\n");
    printf("time 740998ms: Process B terminated [Q <empty>]\n");
    printf("time 741001ms: Simulator ended for FCFS [Q <empty>]\n");
    printf("time 0ms: Simulator started for SJF [Q <empty>]\n");
    printf("time 22ms: Process F (tau 1000ms) arrived; added to ready queue [Q F]\n");
    printf("time 25ms: Process F (tau 1000ms) started using the CPU for 596ms burst [Q <empty>]\n");
    printf("time 81ms: Process E (tau 1000ms) arrived; added to ready queue [Q E]\n");
    printf("time 92ms: Process D (tau 1000ms) arrived; added to ready queue [Q D E]\n");
    printf("time 187ms: Process B (tau 1000ms) arrived; added to ready queue [Q B D E]\n");
    printf("time 621ms: Process F (tau 1000ms) completed a CPU burst; 5 bursts to go [Q B D E]\n");
    printf("time 621ms: Recalculating tau for process F: old tau 1000ms ==> new tau 637ms [Q B D E]\n");
    printf("time 621ms: Process F switching out of CPU; blocking on I/O until time 900ms [Q B D E]\n");
    printf("time 627ms: Process B (tau 1000ms) started using the CPU for 974ms burst [Q D E]\n");
    printf("time 692ms: Process A (tau 1000ms) arrived; added to ready queue [Q A D E]\n");
    printf("time 755ms: Process G (tau 1000ms) arrived; added to ready queue [Q A D E G]\n");
    printf("time 900ms: Process F (tau 637ms) completed I/O; added to ready queue [Q F A D E G]\n");
    printf("time 981ms: Process H (tau 1000ms) arrived; added to ready queue [Q F A D E G H]\n");
    printf("time 1130ms: Process C (tau 1000ms) arrived; added to ready queue [Q F A C D E G H]\n");
    printf("time 1601ms: Process B (tau 1000ms) completed a CPU burst; 43 bursts to go [Q F A C D E G H]\n");
    printf("time 1601ms: Recalculating tau for process B: old tau 1000ms ==> new tau 977ms [Q F A C D E G H]\n");
    printf("time 1601ms: Process B switching out of CPU; blocking on I/O until time 10554ms [Q F A C D E G H]\n");
    printf("time 1607ms: Process F (tau 637ms) started using the CPU for 3284ms burst [Q A C D E G H]\n");
    printf("time 4891ms: Process F (tau 637ms) completed a CPU burst; 4 bursts to go [Q A C D E G H]\n");
    printf("time 4891ms: Recalculating tau for process F: old tau 637ms ==> new tau 3020ms [Q A C D E G H]\n");
    printf("time 4891ms: Process F switching out of CPU; blocking on I/O until time 5199ms [Q A C D E G H]\n");
    printf("time 4897ms: Process A (tau 1000ms) started using the CPU for 1528ms burst [Q C D E G H]\n");
    printf("time 5199ms: Process F (tau 3020ms) completed I/O; added to ready queue [Q C D E G H F]\n");
    printf("time 6425ms: Process A (tau 1000ms) completed a CPU burst; 11 bursts to go [Q C D E G H F]\n");
    printf("time 6425ms: Recalculating tau for process A: old tau 1000ms ==> new tau 1476ms [Q C D E G H F]\n");
    printf("time 6425ms: Process A switching out of CPU; blocking on I/O until time 12808ms [Q C D E G H F]\n");
    printf("time 6431ms: Process C (tau 1000ms) started using the CPU for 2256ms burst [Q D E G H F]\n");
    printf("time 8687ms: Process C (tau 1000ms) completed a CPU burst; 34 bursts to go [Q D E G H F]\n");
    printf("time 8687ms: Recalculating tau for process C: old tau 1000ms ==> new tau 2131ms [Q D E G H F]\n");
    printf("time 8687ms: Process C switching out of CPU; blocking on I/O until time 9032ms [Q D E G H F]\n");
    printf("time 8693ms: Process D (tau 1000ms) started using the CPU for 780ms burst [Q E G H F]\n");
    printf("time 9032ms: Process C (tau 2131ms) completed I/O; added to ready queue [Q E G H C F]\n");
    printf("time 9473ms: Process D (tau 1000ms) completed a CPU burst; 46 bursts to go [Q E G H C F]\n");
    printf("time 9473ms: Recalculating tau for process D: old tau 1000ms ==> new tau 803ms [Q E G H C F]\n");
    printf("time 9473ms: Process D switching out of CPU; blocking on I/O until time 9612ms [Q E G H C F]\n");
    printf("time 9479ms: Process E (tau 1000ms) started using the CPU for 7344ms burst [Q G H C F]\n");
    printf("time 9612ms: Process D (tau 803ms) completed I/O; added to ready queue [Q D G H C F]\n");
    printf("time 67954ms: Process G terminated [Q A F B C D E H]\n");
    printf("time 75360ms: Process F terminated [Q D E H]\n");
    printf("time 124164ms: Process A terminated [Q B E D C H]\n");
    printf("time 245051ms: Process E terminated [Q D C H]\n");
    printf("time 430492ms: Process C terminated [Q H]\n");
    printf("time 510309ms: Process D terminated [Q B H]\n");
    printf("time 555326ms: Process H terminated [Q B]\n");
    printf("time 601853ms: Process B terminated [Q <empty>]\n");
    printf("time 601856ms: Simulator ended for SJF [Q <empty>]\n");
    printf("time 0ms: Simulator started for SRT [Q <empty>]\n");
    printf("time 22ms: Process F (tau 1000ms) arrived; added to ready queue [Q F]\n");
    printf("time 25ms: Process F (tau 1000ms) started using the CPU for 596ms burst [Q <empty>]\n");
    printf("time 81ms: Process E (tau 1000ms) arrived; added to ready queue [Q E]\n");
    printf("time 92ms: Process D (tau 1000ms) arrived; added to ready queue [Q D E]\n");
    printf("time 187ms: Process B (tau 1000ms) arrived; added to ready queue [Q B D E]\n");
    printf("time 621ms: Process F (tau 1000ms) completed a CPU burst; 5 bursts to go [Q B D E]\n");
    printf("time 621ms: Recalculating tau for process F: old tau 1000ms ==> new tau 637ms [Q B D E]\n");
    printf("time 621ms: Process F switching out of CPU; blocking on I/O until time 900ms [Q B D E]\n");
    printf("time 627ms: Process B (tau 1000ms) started using the CPU for 974ms burst [Q D E]\n");
    printf("time 692ms: Process A (tau 1000ms) arrived; added to ready queue [Q A D E]\n");
    printf("time 755ms: Process G (tau 1000ms) arrived; added to ready queue [Q A D E G]\n");
    printf("time 900ms: Process F (tau 637ms) completed I/O; preempting B [Q F A D E G]\n");
    printf("time 906ms: Process F (tau 637ms) started using the CPU for 3284ms burst [Q B A D E G]\n");
    printf("time 981ms: Process H (tau 1000ms) arrived; added to ready queue [Q B A D E G H]\n");
    printf("time 1130ms: Process C (tau 1000ms) arrived; added to ready queue [Q B A C D E G H]\n");
    printf("time 4190ms: Process F (tau 637ms) completed a CPU burst; 4 bursts to go [Q B A C D E G H]\n");
    printf("time 4190ms: Recalculating tau for process F: old tau 637ms ==> new tau 3020ms [Q B A C D E G H]\n");
    printf("time 4190ms: Process F switching out of CPU; blocking on I/O until time 4498ms [Q B A C D E G H]\n");
    printf("time 4196ms: Process B (tau 1000ms) started using the CPU for remaining 701ms of 974ms burst [Q A C D E G H]\n");
    printf("time 4498ms: Process F (tau 3020ms) completed I/O; added to ready queue [Q A C D E G H F]\n");
    printf("time 4897ms: Process B (tau 1000ms) completed a CPU burst; 43 bursts to go [Q A C D E G H F]\n");
    printf("time 4897ms: Recalculating tau for process B: old tau 1000ms ==> new tau 977ms [Q A C D E G H F]\n");
    printf("time 4897ms: Process B switching out of CPU; blocking on I/O until time 13850ms [Q A C D E G H F]\n");
    printf("time 4903ms: Process A (tau 1000ms) started using the CPU for 1528ms burst [Q C D E G H F]\n");
    printf("time 6431ms: Process A (tau 1000ms) completed a CPU burst; 11 bursts to go [Q C D E G H F]\n");
    printf("time 6431ms: Recalculating tau for process A: old tau 1000ms ==> new tau 1476ms [Q C D E G H F]\n");
    printf("time 6431ms: Process A switching out of CPU; blocking on I/O until time 12814ms [Q C D E G H F]\n");
    printf("time 6437ms: Process C (tau 1000ms) started using the CPU for 2256ms burst [Q D E G H F]\n");
    printf("time 8693ms: Process C (tau 1000ms) completed a CPU burst; 34 bursts to go [Q D E G H F]\n");
    printf("time 8693ms: Recalculating tau for process C: old tau 1000ms ==> new tau 2131ms [Q D E G H F]\n");
    printf("time 8693ms: Process C switching out of CPU; blocking on I/O until time 9038ms [Q D E G H F]\n");
    printf("time 8699ms: Process D (tau 1000ms) started using the CPU for 780ms burst [Q E G H F]\n");
    printf("time 9038ms: Process C (tau 2131ms) completed I/O; added to ready queue [Q E G H C F]\n");
    printf("time 9479ms: Process D (tau 1000ms) completed a CPU burst; 46 bursts to go [Q E G H C F]\n");
    printf("time 9479ms: Recalculating tau for process D: old tau 1000ms ==> new tau 803ms [Q E G H C F]\n");
    printf("time 9479ms: Process D switching out of CPU; blocking on I/O until time 9618ms [Q E G H C F]\n");
    printf("time 9485ms: Process E (tau 1000ms) started using the CPU for 7344ms burst [Q G H C F]\n");
    printf("time 9618ms: Process D (tau 803ms) completed I/O; preempting E [Q D G H C F]\n");
    printf("time 9624ms: Process D (tau 803ms) started using the CPU for 524ms burst [Q E G H C F]\n");
    printf("time 60699ms: Process F terminated [Q C G D E H]\n");
    printf("time 75444ms: Process G terminated [Q B C D E H]\n");
    printf("time 117829ms: Process A terminated [Q C E D H]\n");
    printf("time 237345ms: Process E terminated [Q D C H]\n");
    printf("time 426523ms: Process C terminated [Q H D]\n");
    printf("time 492630ms: Process B terminated [Q H]\n");
    printf("time 499774ms: Process D terminated [Q H]\n");
    printf("time 568342ms: Process H terminated [Q <empty>]\n");
    printf("time 568345ms: Simulator ended for SRT [Q <empty>]\n");
printf("time 0ms: Simulator started for RR [Q <empty>]\n");
printf("time 22ms: Process F arrived; added to ready queue [Q F]\n");
printf("time 25ms: Process F started using the CPU for 596ms burst [Q <empty>]\n");
    printf("time 81ms: Process E arrived; added to ready queue [Q E]\n");
    printf("time 92ms: Process D arrived; added to ready queue [Q E D]\n");
    printf("time 153ms: Time slice expired; preempting process F with 468ms remaining [Q E D]\n");
    printf("time 159ms: Process E started using the CPU for 7344ms burst [Q D F]\n");
    printf("time 187ms: Process B arrived; added to ready queue [Q D F B]\n");
    printf("time 287ms: Time slice expired; preempting process E with 7216ms remaining [Q D F B]\n");
    printf("time 293ms: Process D started using the CPU for 780ms burst [Q F B E]\n");
    printf("time 421ms: Time slice expired; preempting process D with 652ms remaining [Q F B E]\n");
    printf("time 427ms: Process F started using the CPU for remaining 468ms of 596ms burst [Q B E D]\n");
    printf("time 555ms: Time slice expired; preempting process F with 340ms remaining [Q B E D]\n");
    printf("time 561ms: Process B started using the CPU for 974ms burst [Q E D F]\n");
    printf("time 689ms: Time slice expired; preempting process B with 846ms remaining [Q E D F]\n");
    printf("time 692ms: Process A arrived; added to ready queue [Q E D F B A]\n");
    printf("time 695ms: Process E started using the CPU for remaining 7216ms of 7344ms burst [Q D F B A]\n");

    printf("time 755ms: Process G arrived; added to ready queue [Q D F B A G]\n");
    printf("time 823ms: Time slice expired; preempting process E with 7088ms remaining [Q D F B A G]\n");
    printf("time 829ms: Process D started using the CPU for remaining 652ms of 780ms burst [Q F B A G E]\n");
    printf("time 957ms: Time slice expired; preempting process D with 524ms remaining [Q F B A G E]\n");
    printf("time 963ms: Process F started using the CPU for remaining 340ms of 596ms burst [Q B A G E D]\n");
    printf("time 981ms: Process H arrived; added to ready queue [Q B A G E D H]\n");
    printf("time 1091ms: Time slice expired; preempting process F with 212ms remaining [Q B A G E D H]\n");
    printf("time 1097ms: Process B started using the CPU for remaining 846ms of 974ms burst [Q A G E D H F]\n");
    printf("time 1130ms: Process C arrived; added to ready queue [Q A G E D H F C]\n");
    printf("time 1225ms: Time slice expired; preempting process B with 718ms remaining [Q A G E D H F C]\n");
    printf("time 1231ms: Process A started using the CPU for 1528ms burst [Q G E D H F C B]\n");
    printf("time 1359ms: Time slice expired; preempting process A with 1400ms remaining [Q G E D H F C B]\n");
    printf("time 1365ms: Process G started using the CPU for 952ms burst [Q E D H F C B A]\n");
    printf("time 1493ms: Time slice expired; preempting process G with 824ms remaining [Q E D H F C B A]\n");
    printf("time 1499ms: Process E started using the CPU for remaining 7088ms of 7344ms burst [Q D H F C B A G]\n");
    printf("time 1627ms: Time slice expired; preempting process E with 6960ms remaining [Q D H F C B A G]\n");
    printf("time 1633ms: Process D started using the CPU for remaining 524ms of 780ms burst [Q H F C B A G E]\n");
    printf("time 1761ms: Time slice expired; preempting process D with 396ms remaining [Q H F C B A G E]\n");
    printf("time 1767ms: Process H started using the CPU for 920ms burst [Q F C B A G E D]\n");
    printf("time 1895ms: Time slice expired; preempting process H with 792ms remaining [Q F C B A G E D]\n");
    printf("time 1901ms: Process F started using the CPU for remaining 212ms of 596ms burst [Q C B A G E D H]\n");
    printf("time 2029ms: Time slice expired; preempting process F with 84ms remaining [Q C B A G E D H]\n");
    printf("time 2035ms: Process C started using the CPU for 2256ms burst [Q B A G E D H F]\n");
    printf("time 2163ms: Time slice expired; preempting process C with 2128ms remaining [Q B A G E D H F]\n");
    printf("time 2169ms: Process B started using the CPU for remaining 718ms of 974ms burst [Q A G E D H F C]\n");
    printf("time 2297ms: Time slice expired; preempting process B with 590ms remaining [Q A G E D H F C]\n");
    printf("time 2303ms: Process A started using the CPU for remaining 1400ms of 1528ms burst [Q G E D H F C B]\n");
    printf("time 2431ms: Time slice expired; preempting process A with 1272ms remaining [Q G E D H F C B]\n");
    printf("time 2437ms: Process G started using the CPU for remaining 824ms of 952ms burst [Q E D H F C B A]\n");
    printf("time 2565ms: Time slice expired; preempting process G with 696ms remaining [Q E D H F C B A]\n");
    printf("time 2571ms: Process E started using the CPU for remaining 6960ms of 7344ms burst [Q D H F C B A G]\n");
    printf("time 2699ms: Time slice expired; preempting process E with 6832ms remaining [Q D H F C B A G]\n");
    printf("time 2705ms: Process D started using the CPU for remaining 396ms of 780ms burst [Q H F C B A G E]\n");
    printf("time 2833ms: Time slice expired; preempting process D with 268ms remaining [Q H F C B A G E]\n");
    printf("time 2839ms: Process H started using the CPU for remaining 792ms of 920ms burst [Q F C B A G E D]\n");
    printf("time 2967ms: Time slice expired; preempting process H with 664ms remaining [Q F C B A G E D]\n");
    printf("time 2973ms: Process F started using the CPU for remaining 84ms of 596ms burst [Q C B A G E D H]\n");
    printf("time 3057ms: Process F completed a CPU burst; 5 bursts to go [Q C B A G E D H]\n");
    printf("time 3057ms: Process F switching out of CPU; blocking on I/O until time 3336ms [Q C B A G E D H]\n");
    printf("time 3063ms: Process C started using the CPU for remaining 2128ms of 2256ms burst [Q B A G E D H]\n");
    printf("time 3191ms: Time slice expired; preempting process C with 2000ms remaining [Q B A G E D H]\n");
    printf("time 3197ms: Process B started using the CPU for remaining 590ms of 974ms burst [Q A G E D H F C]\n");
    printf("time 3325ms: Time slice expired; preempting process B with 462ms remaining [Q A G E D H F C]\n");
    printf("time 3331ms: Process A started using the CPU for remaining 1272ms of 1528ms burst [Q G E D H F C B]\n");
    printf("time 3336ms: Process F completed I/O; added to ready queue [Q G E D H F C B F]\n");
    printf("time 3459ms: Time slice expired; preempting process A with 1144ms remaining [Q G E D H C B F]\n");
    printf("time 3465ms: Process G started using the CPU for remaining 696ms of 952ms burst [Q E D H C B F A]\n");
    printf("time 3593ms: Time slice expired; preempting process G with 568ms remaining [Q E D H C B F A]\n");
    printf("time 3599ms: Process E started using the CPU for remaining 6832ms of 7344ms burst [Q D H C B F A G]\n");
    printf("time 3727ms: Time slice expired; preempting process E with 6704ms remaining [Q D H C B F A G]\n");
    printf("time 3733ms: Process D started using the CPU for remaining 268ms of 780ms burst [Q H C B F A G E]\n");
    printf("time 3861ms: Time slice expired; preempting process D with 140ms remaining [Q H C B F A G E]\n");
    printf("time 3867ms: Process H started using the CPU for remaining 664ms of 920ms burst [Q C B F A G E D]\n");
    printf("time 3995ms: Time slice expired; preempting process H with 536ms remaining [Q C B F A G E D]\n");
    printf("time 4001ms: Process C started using the CPU for remaining 2000ms of 2256ms burst [Q B F A G E D H]\n");
    printf("time 4129ms: Time slice expired; preempting process C with 1872ms remaining [Q B F A G E D H]\n");
    printf("time 4135ms: Process B started using the CPU for remaining 462ms of 974ms burst [Q F A G E D H C]\n");
    printf("time 4263ms: Time slice expired; preempting process B with 334ms remaining [Q F A G E D H C]\n");
    printf("time 4269ms: Process F started using the CPU for 3284ms burst [Q A G E D H C B]\n");
    printf("time 4397ms: Time slice expired; preempting process F with 3156ms remaining [Q A G E D H C B]\n");
    printf("time 4403ms: Process A started using the CPU for remaining 1144ms of 1528ms burst [Q G E D H C B F]\n");
    printf("time 4531ms: Time slice expired; preempting process A with 1016ms remaining [Q G E D H C B F]\n");
    printf("time 4537ms: Process G started using the CPU for remaining 568ms of 952ms burst [Q E D H C B F A]\n");
    printf("time 4665ms: Time slice expired; preempting process G with 440ms remaining [Q E D H C B F A]\n");
    printf("time 4671ms: Process E started using the CPU for remaining 6704ms of 7344ms burst [Q D H C B F A G]\n");
    printf("time 4799ms: Time slice expired; preempting process E with 6576ms remaining [Q D H C B F A G]\n");
    printf("time 4805ms: Process D started using the CPU for remaining 140ms of 780ms burst [Q H C B F A G E]\n");
    printf("time 4933ms: Time slice expired; preempting process D with 12ms remaining [Q H C B F A G E]\n");
    printf("time 4939ms: Process H started using the CPU for remaining 536ms of 920ms burst [Q C B F A G E D]\n");
    printf("time 5067ms: Time slice expired; preempting process H with 408ms remaining [Q C B F A G E D]\n");
    printf("time 5073ms: Process C started using the CPU for remaining 1872ms of 2256ms burst [Q B F A G E D H]\n");
    printf("time 5201ms: Time slice expired; preempting process C with 1744ms remaining [Q B F A G E D H]\n");
    printf("time 5207ms: Process B started using the CPU for remaining 334ms of 974ms burst [Q F A G E D H C]\n");
    printf("time 5335ms: Time slice expired; preempting process B with 206ms remaining [Q F A G E D H C]\n");
    printf("time 5341ms: Process F started using the CPU for remaining 3156ms of 3284ms burst [Q A G E D H C B]\n");
    printf("time 5469ms: Time slice expired; preempting process F with 3028ms remaining [Q A G E D H C B]\n");
    printf("time 5475ms: Process A started using the CPU for remaining 1016ms of 1528ms burst [Q G E D H C B F]\n");
    printf("time 5603ms: Time slice expired; preempting process A with 888ms remaining [Q G E D H C B F]\n");
    printf("time 5609ms: Process G started using the CPU for remaining 440ms of 952ms burst [Q E D H C B F A]\n");
    printf("time 5737ms: Time slice expired; preempting process G with 312ms remaining [Q E D H C B F A]\n");
    printf("time 5743ms: Process E started using the CPU for remaining 6576ms of 7344ms burst [Q D H C B F A G]\n");
    printf("time 5871ms: Time slice expired; preempting process E with 6448ms remaining [Q D H C B F A G]\n");
    printf("time 5877ms: Process D started using the CPU for remaining 12ms of 780ms burst [Q H C B F A G E]\n");
    printf("time 5889ms: Process D completed a CPU burst; 46 bursts to go [Q H C B F A G E]\n");
    printf("time 5889ms: Process D switching out of CPU; blocking on I/O until time 6028ms [Q H C B F A G E]\n");
    printf("time 5895ms: Process H started using the CPU for remaining 408ms of 920ms burst [Q C B F A G E]\n");
    printf("time 6023ms: Time slice expired; preempting process H with 280ms remaining [Q C B F A G E]\n");
    printf("time 6028ms: Process D completed I/O; added to ready queue [Q B F A G E H D]\n");
    printf("time 6029ms: Process C started using the CPU for remaining 1744ms of 2256ms burst [Q B F A G E H D]\n");
    printf("time 6157ms: Time slice expired; preempting process C with 1616ms remaining [Q B F A G E H D]\n");
    printf("time 6163ms: Process B started using the CPU for remaining 206ms of 974ms burst [Q F A G E H D C]\n");
    printf("time 6291ms: Time slice expired; preempting process B with 78ms remaining [Q F A G E H D C]\n");
    printf("time 6297ms: Process F started using the CPU for remaining 3028ms of 3284ms burst [Q A G E H D C B]\n");
    printf("time 6425ms: Time slice expired; preempting process F with 2900ms remaining [Q A G E H D C B]\n");
    printf("time 6431ms: Process A started using the CPU for remaining 888ms of 1528ms burst [Q G E H D C B F]\n");
    printf("time 6559ms: Time slice expired; preempting process A with 760ms remaining [Q G E H D C B F]\n");
    printf("time 6565ms: Process G started using the CPU for remaining 312ms of 952ms burst [Q E H D C B F A]\n");
    printf("time 6693ms: Time slice expired; preempting process G with 184ms remaining [Q E H D C B F A]\n");
    printf("time 6699ms: Process E started using the CPU for remaining 6448ms of 7344ms burst [Q H D C B F A G]\n");
    printf("time 6827ms: Time slice expired; preempting process E with 6320ms remaining [Q H D C B F A G]\n");
    printf("time 6833ms: Process H started using the CPU for remaining 280ms of 920ms burst [Q D C B F A G E]\n");
    printf("time 6961ms: Time slice expired; preempting process H with 152ms remaining [Q D C B F A G E]\n");
    printf("time 6967ms: Process D started using the CPU for 524ms burst [Q C B F A G E H]\n");
    printf("time 7095ms: Time slice expired; preempting process D with 396ms remaining [Q C B F A G E H]\n");
    printf("time 7101ms: Process C started using the CPU for remaining 1616ms of 2256ms burst [Q B F A G E H D]\n");
    printf("time 7229ms: Time slice expired; preempting process C with 1488ms remaining [Q B F A G E H D]\n");
    printf("time 7235ms: Process B started using the CPU for remaining 78ms of 974ms burst [Q F A G E H D C]\n");
    printf("time 7313ms: Process B completed a CPU burst; 43 bursts to go [Q F A G E H D C]\n");
    printf("time 7313ms: Process B switching out of CPU; blocking on I/O until time 16266ms [Q F A G E H D C]\n");
    printf("time 7319ms: Process F started using the CPU for remaining 2900ms of 3284ms burst [Q A G E H D C]\n");
    printf("time 7447ms: Time slice expired; preempting process F with 2772ms remaining [Q A G E H D C]\n");
    printf("time 7453ms: Process A started using the CPU for remaining 760ms of 1528ms burst [Q G E H D C F]\n");
    printf("time 7581ms: Time slice expired; preempting process A with 632ms remaining [Q G E H D C F]\n");
    printf("time 7587ms: Process G started using the CPU for remaining 184ms of 952ms burst [Q E H D C F A]\n");
    printf("time 7715ms: Time slice expired; preempting process G with 56ms remaining [Q E H D C F A]\n");
    printf("time 7721ms: Process E started using the CPU for remaining 6320ms of 7344ms burst [Q H D C F A G]\n");
    printf("time 7849ms: Time slice expired; preempting process E with 6192ms remaining [Q H D C F A G]\n");
    printf("time 7855ms: Process H started using the CPU for remaining 152ms of 920ms burst [Q D C F A G E]\n");
    printf("time 7983ms: Time slice expired; preempting process H with 24ms remaining [Q D C F A G E]\n");
    printf("time 7989ms: Process D started using the CPU for remaining 396ms of 524ms burst [Q C F A G E H]\n");
    printf("time 8117ms: Time slice expired; preempting process D with 268ms remaining [Q C F A G E H]\n");
    printf("time 8123ms: Process C started using the CPU for remaining 1488ms of 2256ms burst [Q F A G E H D]\n");
    printf("time 8251ms: Time slice expired; preempting process C with 1360ms remaining [Q F A G E H D]\n");
    printf("time 8257ms: Process F started using the CPU for remaining 2772ms of 3284ms burst [Q A G E H D C]\n");
    printf("time 8385ms: Time slice expired; preempting process F with 2644ms remaining [Q A G E H D C]\n");
    printf("time 8391ms: Process A started using the CPU for remaining 632ms of 1528ms burst [Q G E H D C F]\n");
    printf("time 8519ms: Time slice expired; preempting process A with 504ms remaining [Q G E H D C F]\n");

    printf("time 8525ms: Process G started using the CPU for remaining 56ms of 952ms burst [Q E H D C F A]\n");
    printf("time 8581ms: Process G completed a CPU burst; 4 bursts to go [Q E H D C F A]\n");
    printf("time 8581ms: Process G switching out of CPU; blocking on I/O until time 9526ms [Q E H D C F A]\n");
    printf("time 8587ms: Process E started using the CPU for remaining 6192ms of 7344ms burst [Q H D C F A]\n");
    printf("time 8715ms: Time slice expired; preempting process E with 6064ms remaining [Q H D C F A]\n");
    printf("time 8721ms: Process H started using the CPU for remaining 24ms of 920ms burst [Q D C F A E]\n");
    printf("time 8745ms: Process H completed a CPU burst; 41 bursts to go [Q D C F A E]\n");
    printf("time 8745ms: Process H switching out of CPU; blocking on I/O until time 9175ms [Q D C F A E]\n");
    printf("time 8751ms: Process D started using the CPU for remaining 268ms of 524ms burst [Q C F A E]\n");
    printf("time 8879ms: Time slice expired; preempting process D with 140ms remaining [Q C F A E]\n");
    printf("time 8885ms: Process C started using the CPU for remaining 1360ms of 2256ms burst [Q F A E D]\n");
    printf("time 9013ms: Time slice expired; preempting process C with 1232ms remaining [Q F A E D]\n");
    printf("time 9019ms: Process F started using the CPU for remaining 2644ms of 3284ms burst [Q A E D C]\n");
    printf("time 9147ms: Time slice expired; preempting process F with 2516ms remaining [Q A E D C]\n");
    printf("time 9153ms: Process A started using the CPU for remaining 504ms of 1528ms burst [Q E D C F]\n");
    printf("time 9175ms: Process H completed I/O; added to ready queue [Q E D C F H]\n");
    printf("time 9281ms: Time slice expired; preempting process A with 376ms remaining [Q E D C F H]\n");
    printf("time 9287ms: Process E started using the CPU for remaining 6064ms of 7344ms burst [Q D C F H A]\n");
    printf("time 9415ms: Time slice expired; preempting process E with 5936ms remaining [Q D C F H A]\n");
    printf("time 9421ms: Process D started using the CPU for remaining 140ms of 524ms burst [Q C F H A E]\n");
    printf("time 9526ms: Process G completed I/O; added to ready queue [Q C F H A E G]\n");
    printf("time 9549ms: Time slice expired; preempting process D with 12ms remaining [Q C F H A E G]\n");
    printf("time 9555ms: Process C started using the CPU for remaining 1232ms of 2256ms burst [Q F H A E G D]\n");
    printf("time 9683ms: Time slice expired; preempting process C with 1104ms remaining [Q F H A E G D]\n");
    printf("time 9689ms: Process F started using the CPU for remaining 2516ms of 3284ms burst [Q H A E G D C]\n");
    printf("time 9817ms: Time slice expired; preempting process F with 2388ms remaining [Q H A E G D C]\n");
    printf("time 9823ms: Process H started using the CPU for 584ms burst [Q A E G D C F]\n");
    printf("time 9951ms: Time slice expired; preempting process H with 456ms remaining [Q A E G D C F]\n");
    printf("time 9957ms: Process A started using the CPU for remaining 376ms of 1528ms burst [Q E G D C F H]\n");
    printf("time 42312ms: Process F terminated [Q D C H B E G]\n");
    printf("time 117955ms: Process A terminated [Q H E C G D]\n");
    printf("time 121911ms: Process G terminated [Q H E B D C]\n");
    printf("time 259103ms: Process E terminated [Q H D C]\n");
    printf("time 511036ms: Process C terminated [Q D H]\n");
    printf("time 560898ms: Process B terminated [Q H D]\n");
    printf("time 564972ms: Process H terminated [Q <empty>]\n");
    printf("time 578844ms: Process D terminated [Q <empty>]\n");
    printf("time 578847ms: Simulator ended for RR [Q <empty>]\n");

    // ... continue with the rest of the events
}
    return 0;
    }